# Config file to use by the Spring Cloud Config server

# Config for Spring Cloud Config client example
salutation:
  formula: '{cypher}40f28a628be173f30f525148effe51d70f363f32b510967b9e797d60e3e497b7'
  tail-question: how are u today?

# Config for Eureka server code sample
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
